### ISSUE TITLE
What could be the reason for Unknown error format?

### ISSUE THREAD

**Issue by kamalpandey** [expo-community/expo-server-sdk-ruby#38]
```
Exponent::Push::UnknownError: Unknown error format: {}
  from exponent-server-sdk (0.1.0) lib/exponent-server-sdk.rb:143:in `handle'
  from exponent-server-sdk (0.1.0) lib/exponent-server-sdk.rb:51:in `publish'
  from app/workers/expo_worker.rb:15:in `perform'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:196:in `execute_job'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
  from sidekiq (6.1.2) lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
  from newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/sidekiq.rb:35:in `block in call'
  from newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/controller_instrumentation.rb:376:in `perform_action_with_newrelic_trace'
  from newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/sidekiq.rb:30:in `call'
  from sidekiq (6.1.2) lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
  from sentry-raven (3.1.1) lib/raven/integrations/sidekiq/cleanup_middleware.rb:7:in `call'
  from sidekiq (6.1.2) lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
  from sidekiq (6.1.2) lib/sidekiq/middleware/chain.rb:143:in `invoke'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:163:in `block in process'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
  from sidekiq (6.1.2) lib/sidekiq/job_retry.rb:111:in `local'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
  from sidekiq (6.1.2) lib/sidekiq/rails.rb:14:in `block in call'
  from activesupport (6.0.3.4) lib/active_support/execution_wrapper.rb:88:in `wrap'
  from activesupport (6.0.3.4) lib/active_support/reloader.rb:72:in `block in wrap'
  from activesupport (6.0.3.4) lib/active_support/execution_wrapper.rb:88:in `wrap'
  from activesupport (6.0.3.4) lib/active_support/reloader.rb:71:in `wrap'
  from sidekiq (6.1.2) lib/sidekiq/rails.rb:13:in `call'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:257:in `stats'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
  from sidekiq (6.1.2) lib/sidekiq/job_logger.rb:13:in `call'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
  from sidekiq (6.1.2) lib/sidekiq/job_retry.rb:78:in `global'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:124:in `block in dispatch'
  from sidekiq (6.1.2) lib/sidekiq/logger.rb:10:in `with'
  from sidekiq (6.1.2) lib/sidekiq/job_logger.rb:33:in `prepare'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:123:in `dispatch'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:162:in `process'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:78:in `process_one'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:68:in `run'
  from sidekiq (6.1.2) lib/sidekiq/util.rb:15:in `watchdog'
  from sidekiq (6.1.2) lib/sidekiq/util.rb:24:in `block in safe_thread'
```

**Comment by foolem** [comment]
You're probably sending more than 100 devices per request. Or you're sending multiple expo-experiences inside token array.
I had exactly these two issues.
